### ISSUE TITLE
Feature Request: allow template for YAML

### ISSUE THREAD

**Issue by AnthonyMcDougal** [PKM-er/obsidian-zotero#164] opened 2023-08-20 01:46 UTC
This is a really neat plugin, thank you! I would like to have more control over the YAML, can you add a template for the YAML? 

I know the plugin needs to have zotero-key and zt-attachments in order to work, so perhaps the template can just be concatenated after those attributes?

Why I need it: 
- Some fields have characters that are problematic for YAML, like ':' etc, and I need to put them in quotes
- Aliases are important for my workflow
- I'd like to customize the visual appearance/layout

**Comment by aidenlx** [comment] 2023-09-02 16:08
duplicate of [#103]

**Closed by aidenlx** 2023-09-02 16:08 UTC
